/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Datetime
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AutoRestDateTimeTestService.
 */
export interface Datetime {


    /**
     * Get null datetime value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getNullWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get null datetime value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getNull(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getNull(callback: ServiceCallback<Date>): void;
    getNull(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get invalid datetime value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getInvalidWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get invalid datetime value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getInvalid(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getInvalid(callback: ServiceCallback<Date>): void;
    getInvalid(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get overflow datetime value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getOverflowWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get overflow datetime value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getOverflow(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getOverflow(callback: ServiceCallback<Date>): void;
    getOverflow(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get underflow datetime value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getUnderflowWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get underflow datetime value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getUnderflow(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getUnderflow(callback: ServiceCallback<Date>): void;
    getUnderflow(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Put max datetime value 9999-12-31T23:59:59.9999999Z
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putUtcMaxDateTimeWithHttpOperationResponse(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Put max datetime value 9999-12-31T23:59:59.9999999Z
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putUtcMaxDateTime(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putUtcMaxDateTime(datetimeBody: Date|string, callback: ServiceCallback<void>): void;
    putUtcMaxDateTime(datetimeBody: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get max datetime value 9999-12-31t23:59:59.9999999z
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getUtcLowercaseMaxDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get max datetime value 9999-12-31t23:59:59.9999999z
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getUtcLowercaseMaxDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getUtcLowercaseMaxDateTime(callback: ServiceCallback<Date>): void;
    getUtcLowercaseMaxDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get max datetime value 9999-12-31T23:59:59.9999999Z
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getUtcUppercaseMaxDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get max datetime value 9999-12-31T23:59:59.9999999Z
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getUtcUppercaseMaxDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getUtcUppercaseMaxDateTime(callback: ServiceCallback<Date>): void;
    getUtcUppercaseMaxDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Put max datetime value with positive numoffset 9999-12-31t23:59:59.9999999+14:00
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putLocalPositiveOffsetMaxDateTimeWithHttpOperationResponse(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Put max datetime value with positive numoffset 9999-12-31t23:59:59.9999999+14:00
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putLocalPositiveOffsetMaxDateTime(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putLocalPositiveOffsetMaxDateTime(datetimeBody: Date|string, callback: ServiceCallback<void>): void;
    putLocalPositiveOffsetMaxDateTime(datetimeBody: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get max datetime value with positive num offset 9999-12-31t23:59:59.9999999+14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getLocalPositiveOffsetLowercaseMaxDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get max datetime value with positive num offset 9999-12-31t23:59:59.9999999+14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getLocalPositiveOffsetLowercaseMaxDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getLocalPositiveOffsetLowercaseMaxDateTime(callback: ServiceCallback<Date>): void;
    getLocalPositiveOffsetLowercaseMaxDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get max datetime value with positive num offset 9999-12-31T23:59:59.9999999+14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getLocalPositiveOffsetUppercaseMaxDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get max datetime value with positive num offset 9999-12-31T23:59:59.9999999+14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getLocalPositiveOffsetUppercaseMaxDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getLocalPositiveOffsetUppercaseMaxDateTime(callback: ServiceCallback<Date>): void;
    getLocalPositiveOffsetUppercaseMaxDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Put max datetime value with positive numoffset 9999-12-31t23:59:59.9999999-14:00
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putLocalNegativeOffsetMaxDateTimeWithHttpOperationResponse(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Put max datetime value with positive numoffset 9999-12-31t23:59:59.9999999-14:00
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putLocalNegativeOffsetMaxDateTime(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putLocalNegativeOffsetMaxDateTime(datetimeBody: Date|string, callback: ServiceCallback<void>): void;
    putLocalNegativeOffsetMaxDateTime(datetimeBody: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get max datetime value with positive num offset 9999-12-31T23:59:59.9999999-14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getLocalNegativeOffsetUppercaseMaxDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get max datetime value with positive num offset 9999-12-31T23:59:59.9999999-14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getLocalNegativeOffsetUppercaseMaxDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getLocalNegativeOffsetUppercaseMaxDateTime(callback: ServiceCallback<Date>): void;
    getLocalNegativeOffsetUppercaseMaxDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get max datetime value with positive num offset 9999-12-31t23:59:59.9999999-14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getLocalNegativeOffsetLowercaseMaxDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get max datetime value with positive num offset 9999-12-31t23:59:59.9999999-14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getLocalNegativeOffsetLowercaseMaxDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getLocalNegativeOffsetLowercaseMaxDateTime(callback: ServiceCallback<Date>): void;
    getLocalNegativeOffsetLowercaseMaxDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Put min datetime value 0001-01-01T00:00:00Z
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putUtcMinDateTimeWithHttpOperationResponse(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Put min datetime value 0001-01-01T00:00:00Z
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putUtcMinDateTime(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putUtcMinDateTime(datetimeBody: Date|string, callback: ServiceCallback<void>): void;
    putUtcMinDateTime(datetimeBody: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get min datetime value 0001-01-01T00:00:00Z
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getUtcMinDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get min datetime value 0001-01-01T00:00:00Z
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getUtcMinDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getUtcMinDateTime(callback: ServiceCallback<Date>): void;
    getUtcMinDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Put min datetime value 0001-01-01T00:00:00+14:00
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putLocalPositiveOffsetMinDateTimeWithHttpOperationResponse(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Put min datetime value 0001-01-01T00:00:00+14:00
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putLocalPositiveOffsetMinDateTime(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putLocalPositiveOffsetMinDateTime(datetimeBody: Date|string, callback: ServiceCallback<void>): void;
    putLocalPositiveOffsetMinDateTime(datetimeBody: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get min datetime value 0001-01-01T00:00:00+14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getLocalPositiveOffsetMinDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get min datetime value 0001-01-01T00:00:00+14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getLocalPositiveOffsetMinDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getLocalPositiveOffsetMinDateTime(callback: ServiceCallback<Date>): void;
    getLocalPositiveOffsetMinDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Put min datetime value 0001-01-01T00:00:00-14:00
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putLocalNegativeOffsetMinDateTimeWithHttpOperationResponse(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Put min datetime value 0001-01-01T00:00:00-14:00
     * @param {date} datetimeBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putLocalNegativeOffsetMinDateTime(datetimeBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putLocalNegativeOffsetMinDateTime(datetimeBody: Date|string, callback: ServiceCallback<void>): void;
    putLocalNegativeOffsetMinDateTime(datetimeBody: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get min datetime value 0001-01-01T00:00:00-14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getLocalNegativeOffsetMinDateTimeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get min datetime value 0001-01-01T00:00:00-14:00
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getLocalNegativeOffsetMinDateTime(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getLocalNegativeOffsetMinDateTime(callback: ServiceCallback<Date>): void;
    getLocalNegativeOffsetMinDateTime(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;
}
