/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Implicit
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AutoRestRequiredOptionalTestService.
 */
export interface Implicit {


    /**
     * Test implicitly required path parameter
     * @param {string} pathParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getRequiredPathWithHttpOperationResponse(pathParameter: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test implicitly required path parameter
     * @param {string} pathParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getRequiredPath(pathParameter: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    getRequiredPath(pathParameter: string, callback: ServiceCallback<models.ErrorModel>): void;
    getRequiredPath(pathParameter: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test implicitly optional query parameter
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.queryParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putOptionalQueryWithHttpOperationResponse(options?: { queryParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test implicitly optional query parameter
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.queryParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putOptionalQuery(options?: { queryParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putOptionalQuery(callback: ServiceCallback<void>): void;
    putOptionalQuery(options: { queryParameter? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test implicitly optional header parameter
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.queryParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putOptionalHeaderWithHttpOperationResponse(options?: { queryParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test implicitly optional header parameter
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.queryParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putOptionalHeader(options?: { queryParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putOptionalHeader(callback: ServiceCallback<void>): void;
    putOptionalHeader(options: { queryParameter? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test implicitly optional body parameter
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putOptionalBodyWithHttpOperationResponse(options?: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test implicitly optional body parameter
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putOptionalBody(options?: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putOptionalBody(callback: ServiceCallback<void>): void;
    putOptionalBody(options: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test implicitly required path parameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getRequiredGlobalPathWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test implicitly required path parameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getRequiredGlobalPath(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    getRequiredGlobalPath(callback: ServiceCallback<models.ErrorModel>): void;
    getRequiredGlobalPath(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test implicitly required query parameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getRequiredGlobalQueryWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test implicitly required query parameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getRequiredGlobalQuery(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    getRequiredGlobalQuery(callback: ServiceCallback<models.ErrorModel>): void;
    getRequiredGlobalQuery(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test implicitly optional query parameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getOptionalGlobalQueryWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test implicitly optional query parameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getOptionalGlobalQuery(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    getOptionalGlobalQuery(callback: ServiceCallback<models.ErrorModel>): void;
    getOptionalGlobalQuery(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;
}

/**
 * @class
 * Explicit
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AutoRestRequiredOptionalTestService.
 */
export interface Explicit {


    /**
     * Test explicitly required integer. Please put null and the client library should throw before the
     * request is sent.
     * @param {number} bodyParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredIntegerParameterWithHttpOperationResponse(bodyParameter: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required integer. Please put null and the client library should throw before the
     * request is sent.
     * @param {number} bodyParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredIntegerParameter(bodyParameter: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredIntegerParameter(bodyParameter: number, callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredIntegerParameter(bodyParameter: number, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional integer. Please put null.
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalIntegerParameterWithHttpOperationResponse(options?: { bodyParameter? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional integer. Please put null.
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalIntegerParameter(options?: { bodyParameter? : number, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalIntegerParameter(callback: ServiceCallback<void>): void;
    postOptionalIntegerParameter(options: { bodyParameter? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required integer. Please put a valid int-wrapper with 'value' = null and the
     * client library should throw before the request is sent.
     * @param {number} value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredIntegerPropertyWithHttpOperationResponse(value: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required integer. Please put a valid int-wrapper with 'value' = null and the
     * client library should throw before the request is sent.
     * @param {number} value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredIntegerProperty(value: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredIntegerProperty(value: number, callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredIntegerProperty(value: number, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional integer. Please put a valid int-wrapper with 'value' = null.
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.value]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalIntegerPropertyWithHttpOperationResponse(options?: { value? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional integer. Please put a valid int-wrapper with 'value' = null.
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.value]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalIntegerProperty(options?: { value? : number, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalIntegerProperty(callback: ServiceCallback<void>): void;
    postOptionalIntegerProperty(options: { value? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required integer. Please put a header 'headerParameter' => null and the client
     * library should throw before the request is sent.
     * @param {number} headerParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredIntegerHeaderWithHttpOperationResponse(headerParameter: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required integer. Please put a header 'headerParameter' => null and the client
     * library should throw before the request is sent.
     * @param {number} headerParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredIntegerHeader(headerParameter: number, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredIntegerHeader(headerParameter: number, callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredIntegerHeader(headerParameter: number, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional integer. Please put a header 'headerParameter' => null.
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.headerParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalIntegerHeaderWithHttpOperationResponse(options?: { headerParameter? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional integer. Please put a header 'headerParameter' => null.
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.headerParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalIntegerHeader(options?: { headerParameter? : number, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalIntegerHeader(callback: ServiceCallback<void>): void;
    postOptionalIntegerHeader(options: { headerParameter? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required string. Please put null and the client library should throw before the
     * request is sent.
     * @param {string} bodyParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredStringParameterWithHttpOperationResponse(bodyParameter: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required string. Please put null and the client library should throw before the
     * request is sent.
     * @param {string} bodyParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredStringParameter(bodyParameter: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredStringParameter(bodyParameter: string, callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredStringParameter(bodyParameter: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional string. Please put null.
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalStringParameterWithHttpOperationResponse(options?: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional string. Please put null.
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalStringParameter(options?: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalStringParameter(callback: ServiceCallback<void>): void;
    postOptionalStringParameter(options: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required string. Please put a valid string-wrapper with 'value' = null and the
     * client library should throw before the request is sent.
     * @param {string} value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredStringPropertyWithHttpOperationResponse(value: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required string. Please put a valid string-wrapper with 'value' = null and the
     * client library should throw before the request is sent.
     * @param {string} value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredStringProperty(value: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredStringProperty(value: string, callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredStringProperty(value: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional integer. Please put a valid string-wrapper with 'value' = null.
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.value]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalStringPropertyWithHttpOperationResponse(options?: { value? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional integer. Please put a valid string-wrapper with 'value' = null.
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.value]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalStringProperty(options?: { value? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalStringProperty(callback: ServiceCallback<void>): void;
    postOptionalStringProperty(options: { value? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required string. Please put a header 'headerParameter' => null and the client
     * library should throw before the request is sent.
     * @param {string} headerParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredStringHeaderWithHttpOperationResponse(headerParameter: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required string. Please put a header 'headerParameter' => null and the client
     * library should throw before the request is sent.
     * @param {string} headerParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredStringHeader(headerParameter: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredStringHeader(headerParameter: string, callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredStringHeader(headerParameter: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional string. Please put a header 'headerParameter' => null.
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalStringHeaderWithHttpOperationResponse(options?: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional string. Please put a header 'headerParameter' => null.
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalStringHeader(options?: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalStringHeader(callback: ServiceCallback<void>): void;
    postOptionalStringHeader(options: { bodyParameter? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required complex object. Please put null and the client library should throw
     * before the request is sent.
     * @param {object} bodyParameter
     * @param {number} bodyParameter.id
     * @param {string} [bodyParameter.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredClassParameterWithHttpOperationResponse(bodyParameter: models.Product, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required complex object. Please put null and the client library should throw
     * before the request is sent.
     * @param {object} bodyParameter
     * @param {number} bodyParameter.id
     * @param {string} [bodyParameter.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredClassParameter(bodyParameter: models.Product, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredClassParameter(bodyParameter: models.Product, callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredClassParameter(bodyParameter: models.Product, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional complex object. Please put null.
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.bodyParameter]
     * @param {number} options.bodyParameter.id
     * @param {string} [options.bodyParameter.name]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalClassParameterWithHttpOperationResponse(options?: { bodyParameter? : models.Product, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional complex object. Please put null.
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.bodyParameter]
     * @param {number} options.bodyParameter.id
     * @param {string} [options.bodyParameter.name]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalClassParameter(options?: { bodyParameter? : models.Product, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalClassParameter(callback: ServiceCallback<void>): void;
    postOptionalClassParameter(options: { bodyParameter? : models.Product, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required complex object. Please put a valid class-wrapper with 'value' = null
     * and the client library should throw before the request is sent.
     * @param {object} value
     * @param {number} value.id
     * @param {string} [value.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredClassPropertyWithHttpOperationResponse(value: models.Product, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required complex object. Please put a valid class-wrapper with 'value' = null
     * and the client library should throw before the request is sent.
     * @param {object} value
     * @param {number} value.id
     * @param {string} [value.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredClassProperty(value: models.Product, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredClassProperty(value: models.Product, callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredClassProperty(value: models.Product, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional complex object. Please put a valid class-wrapper with 'value' = null.
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.value]
     * @param {number} options.value.id
     * @param {string} [options.value.name]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalClassPropertyWithHttpOperationResponse(options?: { value? : models.Product, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional complex object. Please put a valid class-wrapper with 'value' = null.
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.value]
     * @param {number} options.value.id
     * @param {string} [options.value.name]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalClassProperty(options?: { value? : models.Product, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalClassProperty(callback: ServiceCallback<void>): void;
    postOptionalClassProperty(options: { value? : models.Product, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required array. Please put null and the client library should throw before the
     * request is sent.
     * @param {array} bodyParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredArrayParameterWithHttpOperationResponse(bodyParameter: string[], options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required array. Please put null and the client library should throw before the
     * request is sent.
     * @param {array} bodyParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredArrayParameter(bodyParameter: string[], options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredArrayParameter(bodyParameter: string[], callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredArrayParameter(bodyParameter: string[], options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional array. Please put null.
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalArrayParameterWithHttpOperationResponse(options?: { bodyParameter? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional array. Please put null.
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.bodyParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalArrayParameter(options?: { bodyParameter? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalArrayParameter(callback: ServiceCallback<void>): void;
    postOptionalArrayParameter(options: { bodyParameter? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required array. Please put a valid array-wrapper with 'value' = null and the
     * client library should throw before the request is sent.
     * @param {array} value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredArrayPropertyWithHttpOperationResponse(value: string[], options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required array. Please put a valid array-wrapper with 'value' = null and the
     * client library should throw before the request is sent.
     * @param {array} value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredArrayProperty(value: string[], options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredArrayProperty(value: string[], callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredArrayProperty(value: string[], options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional array. Please put a valid array-wrapper with 'value' = null.
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.value]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalArrayPropertyWithHttpOperationResponse(options?: { value? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional array. Please put a valid array-wrapper with 'value' = null.
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.value]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalArrayProperty(options?: { value? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalArrayProperty(callback: ServiceCallback<void>): void;
    postOptionalArrayProperty(options: { value? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Test explicitly required array. Please put a header 'headerParameter' => null and the client
     * library should throw before the request is sent.
     * @param {array} headerParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postRequiredArrayHeaderWithHttpOperationResponse(headerParameter: string[], options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.ErrorModel>>;

    /**
     * Test explicitly required array. Please put a header 'headerParameter' => null and the client
     * library should throw before the request is sent.
     * @param {array} headerParameter
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postRequiredArrayHeader(headerParameter: string[], options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.ErrorModel>;
    postRequiredArrayHeader(headerParameter: string[], callback: ServiceCallback<models.ErrorModel>): void;
    postRequiredArrayHeader(headerParameter: string[], options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.ErrorModel>): void;


    /**
     * Test explicitly optional integer. Please put a header 'headerParameter' => null.
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.headerParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    postOptionalArrayHeaderWithHttpOperationResponse(options?: { headerParameter? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Test explicitly optional integer. Please put a header 'headerParameter' => null.
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.headerParameter]
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    postOptionalArrayHeader(options?: { headerParameter? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    postOptionalArrayHeader(callback: ServiceCallback<void>): void;
    postOptionalArrayHeader(options: { headerParameter? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;
}
