/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The URIs that are used to perform a retrieval of a public blob, queue or
 * table object.
 *
 */
class Foo {
  /**
   * Create a Foo.
   * @property {object} [barPoint] Bar point
   * @property {object} [barPoint.recursivePoint] Recursive Endpoints
   * @property {string} [barPoint.recursivePoint.blob] Gets the blob endpoint.
   * @property {string} [barPoint.recursivePoint.queue] Gets the queue
   * endpoint.
   * @property {string} [barPoint.recursivePoint.table] Gets the table
   * endpoint.
   * @property {object} [barPoint.recursivePoint.dummyEndPoint] Dummy EndPoint
   * @property {object} [barPoint.recursivePoint.fooPoint] Foo point
   */
  constructor() {
  }

  /**
   * Defines the metadata of Foo
   *
   * @returns {object} metadata of Foo
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Foo',
      type: {
        name: 'Composite',
        className: 'Foo',
        modelProperties: {
          barPoint: {
            required: false,
            serializedName: 'Bar\\.Point',
            type: {
              name: 'Composite',
              className: 'Bar'
            }
          }
        }
      }
    };
  }
}

module.exports = Foo;
