/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a Pet.
 */
class Pet {
  /**
   * Create a Pet.
   * @property {string} [name]
   * @property {string} [daysOfWeek] Type of Pet. Possible values include:
   * 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
   * 'Sunday'. Default value: 'Friday' .
   * @property {string} intEnum Possible values include: '1', '2', '3'
   */
  constructor() {
  }

  /**
   * Defines the metadata of Pet
   *
   * @returns {object} metadata of Pet
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Pet',
      type: {
        name: 'Composite',
        className: 'Pet',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          daysOfWeek: {
            required: false,
            serializedName: 'DaysOfWeek',
            defaultValue: 'Friday',
            type: {
              name: 'String'
            }
          },
          intEnum: {
            required: true,
            serializedName: 'IntEnum',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Pet;
