/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

exports.ErrorModel = require('./errorModel');
exports.PetAPTrue = require('./petAPTrue');
exports.CatAPTrue = require('./catAPTrue');
exports.PetAPObject = require('./petAPObject');
exports.PetAPString = require('./petAPString');
exports.PetAPInProperties = require('./petAPInProperties');
exports.PetAPInPropertiesWithAPString = require('./petAPInPropertiesWithAPString');
