/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a PetAPString.
 */
class PetAPString {
  /**
   * Create a PetAPString.
   * @member {number} id
   * @member {string} [name]
   * @member {boolean} [status]
   */
  constructor() {
  }

  /**
   * Defines the metadata of PetAPString
   *
   * @returns {object} metadata of PetAPString
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PetAPString',
      type: {
        name: 'Composite',
        additionalProperties: {
          type: {
            name: 'Dictionary',
            value: {
                required: false,
                serializedName: 'StringElementType',
                type: {
                  name: 'String'
                }
            }
          }
        },
        className: 'PetAPString',
        modelProperties: {
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          status: {
            required: false,
            readOnly: true,
            serializedName: 'status',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = PetAPString;
