/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * DateModel
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AutoRestDateTestService.
 */
export interface DateModel {


    /**
     * Get null date value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getNullWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get null date value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getNull(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getNull(callback: ServiceCallback<Date>): void;
    getNull(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get invalid date value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getInvalidDateWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get invalid date value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getInvalidDate(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getInvalidDate(callback: ServiceCallback<Date>): void;
    getInvalidDate(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get overflow date value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getOverflowDateWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get overflow date value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getOverflowDate(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getOverflowDate(callback: ServiceCallback<Date>): void;
    getOverflowDate(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Get underflow date value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getUnderflowDateWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get underflow date value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getUnderflowDate(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getUnderflowDate(callback: ServiceCallback<Date>): void;
    getUnderflowDate(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Put max date value 9999-12-31
     * @param {date} dateBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putMaxDateWithHttpOperationResponse(dateBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Put max date value 9999-12-31
     * @param {date} dateBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putMaxDate(dateBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putMaxDate(dateBody: Date|string, callback: ServiceCallback<void>): void;
    putMaxDate(dateBody: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get max date value 9999-12-31
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getMaxDateWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get max date value 9999-12-31
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getMaxDate(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getMaxDate(callback: ServiceCallback<Date>): void;
    getMaxDate(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;


    /**
     * Put min date value 0000-01-01
     * @param {date} dateBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    putMinDateWithHttpOperationResponse(dateBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Put min date value 0000-01-01
     * @param {date} dateBody
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    putMinDate(dateBody: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    putMinDate(dateBody: Date|string, callback: ServiceCallback<void>): void;
    putMinDate(dateBody: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get min date value 0000-01-01
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getMinDateWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<Date>>;

    /**
     * Get min date value 0000-01-01
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getMinDate(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<Date>;
    getMinDate(callback: ServiceCallback<Date>): void;
    getMinDate(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<Date>): void;
}
