/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { BaseResource, CloudError } from "ms-rest-azure";
import * as moment from "moment";

export {

  BaseResource,
  CloudError
};

export interface Resource extends BaseResource {
  /**
   * Resource Id
  */
  readonly id?: string;
  /**
   * Resource Type
  */
  readonly type?: string;
  tags?: { [propertyName: string]: string };
  /**
   * Resource Location
  */
  location?: string;
  /**
   * Resource Name
  */
  readonly name?: string;
}

export interface Sku {
  name?: string;
  id?: string;
}

export interface Product extends Resource {
  provisioningState?: string;
  /**
   * Possible values include: 'Succeeded', 'Failed', 'canceled', 'Accepted', 'Creating', 'Created',
   * 'Updating', 'Updated', 'Deleting', 'Deleted', 'OK'
  */
  readonly provisioningStateValues?: string;
}

export interface SubResource extends BaseResource {
  /**
   * Sub Resource Id
  */
  readonly id?: string;
}

export interface SubProduct extends SubResource {
  provisioningState?: string;
  /**
   * Possible values include: 'Succeeded', 'Failed', 'canceled', 'Accepted', 'Creating', 'Created',
   * 'Updating', 'Updated', 'Deleting', 'Deleted', 'OK'
  */
  readonly provisioningStateValues?: string;
}

export interface OperationResultError {
  /**
   * The error code for an operation failure
  */
  code?: number;
  /**
   * The detailed arror message
  */
  message?: string;
}

export interface OperationResult {
  /**
   * The status of the request. Possible values include: 'Succeeded', 'Failed', 'canceled',
   * 'Accepted', 'Creating', 'Created', 'Updating', 'Updated', 'Deleting', 'Deleted', 'OK'
  */
  status?: string;
  error?: OperationResultError;
}
