/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Paths
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AutoRestUrlTestService.
 */
export interface Paths {


    /**
     * Get true Boolean value on path
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getBooleanTrueWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get true Boolean value on path
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getBooleanTrue(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getBooleanTrue(callback: ServiceCallback<void>): void;
    getBooleanTrue(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get false Boolean value on path
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getBooleanFalseWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get false Boolean value on path
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getBooleanFalse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getBooleanFalse(callback: ServiceCallback<void>): void;
    getBooleanFalse(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '1000000' integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getIntOneMillionWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '1000000' integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getIntOneMillion(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getIntOneMillion(callback: ServiceCallback<void>): void;
    getIntOneMillion(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '-1000000' integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getIntNegativeOneMillionWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '-1000000' integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getIntNegativeOneMillion(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getIntNegativeOneMillion(callback: ServiceCallback<void>): void;
    getIntNegativeOneMillion(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '10000000000' 64 bit integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getTenBillionWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '10000000000' 64 bit integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getTenBillion(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getTenBillion(callback: ServiceCallback<void>): void;
    getTenBillion(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '-10000000000' 64 bit integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getNegativeTenBillionWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '-10000000000' 64 bit integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getNegativeTenBillion(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getNegativeTenBillion(callback: ServiceCallback<void>): void;
    getNegativeTenBillion(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '1.034E+20' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    floatScientificPositiveWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '1.034E+20' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    floatScientificPositive(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    floatScientificPositive(callback: ServiceCallback<void>): void;
    floatScientificPositive(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '-1.034E-20' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    floatScientificNegativeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '-1.034E-20' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    floatScientificNegative(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    floatScientificNegative(callback: ServiceCallback<void>): void;
    floatScientificNegative(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '9999999.999' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    doubleDecimalPositiveWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '9999999.999' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    doubleDecimalPositive(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    doubleDecimalPositive(callback: ServiceCallback<void>): void;
    doubleDecimalPositive(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '-9999999.999' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    doubleDecimalNegativeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '-9999999.999' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    doubleDecimalNegative(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    doubleDecimalNegative(callback: ServiceCallback<void>): void;
    doubleDecimalNegative(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '啊齄丂狛狜隣郎隣兀﨩' multi-byte string value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    stringUnicodeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '啊齄丂狛狜隣郎隣兀﨩' multi-byte string value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    stringUnicode(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    stringUnicode(callback: ServiceCallback<void>): void;
    stringUnicode(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get 'begin!*'();:@ &=+$,/?#[]end
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    stringUrlEncodedWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get 'begin!*'();:@ &=+$,/?#[]end
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    stringUrlEncoded(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    stringUrlEncoded(callback: ServiceCallback<void>): void;
    stringUrlEncoded(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get ''
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    stringEmptyWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get ''
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    stringEmpty(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    stringEmpty(callback: ServiceCallback<void>): void;
    stringEmpty(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null (should throw)
     * @param {string} stringPath null string value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    stringNullWithHttpOperationResponse(stringPath: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null (should throw)
     * @param {string} stringPath null string value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    stringNull(stringPath: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    stringNull(stringPath: string, callback: ServiceCallback<void>): void;
    stringNull(stringPath: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get using uri with 'green color' in path parameter
     * @param {string} enumPath send the value green. Possible values include: 'red color', 'green
     * color', 'blue color'
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    enumValidWithHttpOperationResponse(enumPath: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get using uri with 'green color' in path parameter
     * @param {string} enumPath send the value green. Possible values include: 'red color', 'green
     * color', 'blue color'
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    enumValid(enumPath: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    enumValid(enumPath: string, callback: ServiceCallback<void>): void;
    enumValid(enumPath: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null (should throw on the client before the request is sent on wire)
     * @param {string} enumPath send null should throw. Possible values include: 'red color', 'green
     * color', 'blue color'
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    enumNullWithHttpOperationResponse(enumPath: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null (should throw on the client before the request is sent on wire)
     * @param {string} enumPath send null should throw. Possible values include: 'red color', 'green
     * color', 'blue color'
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    enumNull(enumPath: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    enumNull(enumPath: string, callback: ServiceCallback<void>): void;
    enumNull(enumPath: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '啊齄丂狛狜隣郎隣兀﨩' multibyte value as utf-8 encoded byte array
     * @param {buffer} bytePath '啊齄丂狛狜隣郎隣兀﨩' multibyte value as utf-8 encoded byte array
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    byteMultiByteWithHttpOperationResponse(bytePath: Buffer, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '啊齄丂狛狜隣郎隣兀﨩' multibyte value as utf-8 encoded byte array
     * @param {buffer} bytePath '啊齄丂狛狜隣郎隣兀﨩' multibyte value as utf-8 encoded byte array
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    byteMultiByte(bytePath: Buffer, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    byteMultiByte(bytePath: Buffer, callback: ServiceCallback<void>): void;
    byteMultiByte(bytePath: Buffer, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '' as byte array
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    byteEmptyWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '' as byte array
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    byteEmpty(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    byteEmpty(callback: ServiceCallback<void>): void;
    byteEmpty(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null as byte array (should throw)
     * @param {buffer} bytePath null as byte array (should throw)
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    byteNullWithHttpOperationResponse(bytePath: Buffer, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null as byte array (should throw)
     * @param {buffer} bytePath null as byte array (should throw)
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    byteNull(bytePath: Buffer, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    byteNull(bytePath: Buffer, callback: ServiceCallback<void>): void;
    byteNull(bytePath: Buffer, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '2012-01-01' as date
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    dateValidWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '2012-01-01' as date
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    dateValid(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    dateValid(callback: ServiceCallback<void>): void;
    dateValid(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null as date - this should throw or be unusable on the client side, depending on date
     * representation
     * @param {date} datePath null as date (should throw)
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    dateNullWithHttpOperationResponse(datePath: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null as date - this should throw or be unusable on the client side, depending on date
     * representation
     * @param {date} datePath null as date (should throw)
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    dateNull(datePath: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    dateNull(datePath: Date|string, callback: ServiceCallback<void>): void;
    dateNull(datePath: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '2012-01-01T01:01:01Z' as date-time
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    dateTimeValidWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '2012-01-01T01:01:01Z' as date-time
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    dateTimeValid(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    dateTimeValid(callback: ServiceCallback<void>): void;
    dateTimeValid(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null as date-time, should be disallowed or throw depending on representation of date-time
     * @param {date} dateTimePath null as date-time
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    dateTimeNullWithHttpOperationResponse(dateTimePath: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null as date-time, should be disallowed or throw depending on representation of date-time
     * @param {date} dateTimePath null as date-time
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    dateTimeNull(dateTimePath: Date|string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    dateTimeNull(dateTimePath: Date|string, callback: ServiceCallback<void>): void;
    dateTimeNull(dateTimePath: Date|string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get 'lorem' encoded value as 'bG9yZW0' (base64url)
     * @param {buffer} base64UrlPath base64url encoded value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    base64UrlWithHttpOperationResponse(base64UrlPath: Buffer, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get 'lorem' encoded value as 'bG9yZW0' (base64url)
     * @param {buffer} base64UrlPath base64url encoded value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    base64Url(base64UrlPath: Buffer, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    base64Url(base64UrlPath: Buffer, callback: ServiceCallback<void>): void;
    base64Url(base64UrlPath: Buffer, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get an array of string ['ArrayPath1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * csv-array format
     * @param {array} arrayPath an array of string ['ArrayPath1', 'begin!*'();:@ &=+$,/?#[]end' , null,
     * ''] using the csv-array format
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    arrayCsvInPathWithHttpOperationResponse(arrayPath: string[], options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get an array of string ['ArrayPath1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * csv-array format
     * @param {array} arrayPath an array of string ['ArrayPath1', 'begin!*'();:@ &=+$,/?#[]end' , null,
     * ''] using the csv-array format
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    arrayCsvInPath(arrayPath: string[], options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    arrayCsvInPath(arrayPath: string[], callback: ServiceCallback<void>): void;
    arrayCsvInPath(arrayPath: string[], options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get the date 2016-04-13 encoded value as '1460505600' (Unix time)
     * @param {date} unixTimeUrlPath Unix time encoded value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    unixTimeUrlWithHttpOperationResponse(unixTimeUrlPath: Date, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get the date 2016-04-13 encoded value as '1460505600' (Unix time)
     * @param {date} unixTimeUrlPath Unix time encoded value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    unixTimeUrl(unixTimeUrlPath: Date, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    unixTimeUrl(unixTimeUrlPath: Date, callback: ServiceCallback<void>): void;
    unixTimeUrl(unixTimeUrlPath: Date, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;
}

/**
 * @class
 * Queries
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AutoRestUrlTestService.
 */
export interface Queries {


    /**
     * Get true Boolean value on path
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getBooleanTrueWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get true Boolean value on path
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getBooleanTrue(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getBooleanTrue(callback: ServiceCallback<void>): void;
    getBooleanTrue(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get false Boolean value on path
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getBooleanFalseWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get false Boolean value on path
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getBooleanFalse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getBooleanFalse(callback: ServiceCallback<void>): void;
    getBooleanFalse(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null Boolean value on query (query string should be absent)
     * @param {object} [options] Optional Parameters.
     * @param {boolean} [options.boolQuery] null boolean value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getBooleanNullWithHttpOperationResponse(options?: { boolQuery? : boolean, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null Boolean value on query (query string should be absent)
     * @param {object} [options] Optional Parameters.
     * @param {boolean} [options.boolQuery] null boolean value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getBooleanNull(options?: { boolQuery? : boolean, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getBooleanNull(callback: ServiceCallback<void>): void;
    getBooleanNull(options: { boolQuery? : boolean, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '1000000' integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getIntOneMillionWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '1000000' integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getIntOneMillion(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getIntOneMillion(callback: ServiceCallback<void>): void;
    getIntOneMillion(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '-1000000' integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getIntNegativeOneMillionWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '-1000000' integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getIntNegativeOneMillion(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getIntNegativeOneMillion(callback: ServiceCallback<void>): void;
    getIntNegativeOneMillion(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null integer value (no query parameter)
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.intQuery] null integer value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getIntNullWithHttpOperationResponse(options?: { intQuery? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null integer value (no query parameter)
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.intQuery] null integer value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getIntNull(options?: { intQuery? : number, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getIntNull(callback: ServiceCallback<void>): void;
    getIntNull(options: { intQuery? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '10000000000' 64 bit integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getTenBillionWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '10000000000' 64 bit integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getTenBillion(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getTenBillion(callback: ServiceCallback<void>): void;
    getTenBillion(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '-10000000000' 64 bit integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getNegativeTenBillionWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '-10000000000' 64 bit integer value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getNegativeTenBillion(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getNegativeTenBillion(callback: ServiceCallback<void>): void;
    getNegativeTenBillion(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get 'null 64 bit integer value (no query param in uri)
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.longQuery] null 64 bit integer value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getLongNullWithHttpOperationResponse(options?: { longQuery? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get 'null 64 bit integer value (no query param in uri)
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.longQuery] null 64 bit integer value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getLongNull(options?: { longQuery? : number, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getLongNull(callback: ServiceCallback<void>): void;
    getLongNull(options: { longQuery? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '1.034E+20' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    floatScientificPositiveWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '1.034E+20' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    floatScientificPositive(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    floatScientificPositive(callback: ServiceCallback<void>): void;
    floatScientificPositive(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '-1.034E-20' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    floatScientificNegativeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '-1.034E-20' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    floatScientificNegative(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    floatScientificNegative(callback: ServiceCallback<void>): void;
    floatScientificNegative(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null numeric value (no query parameter)
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.floatQuery] null numeric value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    floatNullWithHttpOperationResponse(options?: { floatQuery? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null numeric value (no query parameter)
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.floatQuery] null numeric value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    floatNull(options?: { floatQuery? : number, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    floatNull(callback: ServiceCallback<void>): void;
    floatNull(options: { floatQuery? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '9999999.999' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    doubleDecimalPositiveWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '9999999.999' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    doubleDecimalPositive(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    doubleDecimalPositive(callback: ServiceCallback<void>): void;
    doubleDecimalPositive(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '-9999999.999' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    doubleDecimalNegativeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '-9999999.999' numeric value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    doubleDecimalNegative(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    doubleDecimalNegative(callback: ServiceCallback<void>): void;
    doubleDecimalNegative(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null numeric value (no query parameter)
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.doubleQuery] null numeric value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    doubleNullWithHttpOperationResponse(options?: { doubleQuery? : number, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null numeric value (no query parameter)
     * @param {object} [options] Optional Parameters.
     * @param {number} [options.doubleQuery] null numeric value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    doubleNull(options?: { doubleQuery? : number, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    doubleNull(callback: ServiceCallback<void>): void;
    doubleNull(options: { doubleQuery? : number, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '啊齄丂狛狜隣郎隣兀﨩' multi-byte string value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    stringUnicodeWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '啊齄丂狛狜隣郎隣兀﨩' multi-byte string value
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    stringUnicode(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    stringUnicode(callback: ServiceCallback<void>): void;
    stringUnicode(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get 'begin!*'();:@ &=+$,/?#[]end
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    stringUrlEncodedWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get 'begin!*'();:@ &=+$,/?#[]end
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    stringUrlEncoded(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    stringUrlEncoded(callback: ServiceCallback<void>): void;
    stringUrlEncoded(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get ''
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    stringEmptyWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get ''
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    stringEmpty(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    stringEmpty(callback: ServiceCallback<void>): void;
    stringEmpty(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null (no query parameter in url)
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.stringQuery] null string value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    stringNullWithHttpOperationResponse(options?: { stringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null (no query parameter in url)
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.stringQuery] null string value
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    stringNull(options?: { stringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    stringNull(callback: ServiceCallback<void>): void;
    stringNull(options: { stringQuery? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get using uri with query parameter 'green color'
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.enumQuery] 'green color' enum value. Possible values include: 'red
     * color', 'green color', 'blue color'
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    enumValidWithHttpOperationResponse(options?: { enumQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get using uri with query parameter 'green color'
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.enumQuery] 'green color' enum value. Possible values include: 'red
     * color', 'green color', 'blue color'
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    enumValid(options?: { enumQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    enumValid(callback: ServiceCallback<void>): void;
    enumValid(options: { enumQuery? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null (no query parameter in url)
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.enumQuery] null string value. Possible values include: 'red color',
     * 'green color', 'blue color'
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    enumNullWithHttpOperationResponse(options?: { enumQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null (no query parameter in url)
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.enumQuery] null string value. Possible values include: 'red color',
     * 'green color', 'blue color'
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    enumNull(options?: { enumQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    enumNull(callback: ServiceCallback<void>): void;
    enumNull(options: { enumQuery? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '啊齄丂狛狜隣郎隣兀﨩' multibyte value as utf-8 encoded byte array
     * @param {object} [options] Optional Parameters.
     * @param {buffer} [options.byteQuery] '啊齄丂狛狜隣郎隣兀﨩' multibyte value as utf-8 encoded byte array
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    byteMultiByteWithHttpOperationResponse(options?: { byteQuery? : Buffer, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '啊齄丂狛狜隣郎隣兀﨩' multibyte value as utf-8 encoded byte array
     * @param {object} [options] Optional Parameters.
     * @param {buffer} [options.byteQuery] '啊齄丂狛狜隣郎隣兀﨩' multibyte value as utf-8 encoded byte array
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    byteMultiByte(options?: { byteQuery? : Buffer, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    byteMultiByte(callback: ServiceCallback<void>): void;
    byteMultiByte(options: { byteQuery? : Buffer, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '' as byte array
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    byteEmptyWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '' as byte array
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    byteEmpty(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    byteEmpty(callback: ServiceCallback<void>): void;
    byteEmpty(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null as byte array (no query parameters in uri)
     * @param {object} [options] Optional Parameters.
     * @param {buffer} [options.byteQuery] null as byte array (no query parameters in uri)
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    byteNullWithHttpOperationResponse(options?: { byteQuery? : Buffer, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null as byte array (no query parameters in uri)
     * @param {object} [options] Optional Parameters.
     * @param {buffer} [options.byteQuery] null as byte array (no query parameters in uri)
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    byteNull(options?: { byteQuery? : Buffer, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    byteNull(callback: ServiceCallback<void>): void;
    byteNull(options: { byteQuery? : Buffer, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '2012-01-01' as date
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    dateValidWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '2012-01-01' as date
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    dateValid(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    dateValid(callback: ServiceCallback<void>): void;
    dateValid(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null as date - this should result in no query parameters in uri
     * @param {object} [options] Optional Parameters.
     * @param {date} [options.dateQuery] null as date (no query parameters in uri)
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    dateNullWithHttpOperationResponse(options?: { dateQuery? : Date, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null as date - this should result in no query parameters in uri
     * @param {object} [options] Optional Parameters.
     * @param {date} [options.dateQuery] null as date (no query parameters in uri)
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    dateNull(options?: { dateQuery? : Date, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    dateNull(callback: ServiceCallback<void>): void;
    dateNull(options: { dateQuery? : Date, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get '2012-01-01T01:01:01Z' as date-time
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    dateTimeValidWithHttpOperationResponse(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get '2012-01-01T01:01:01Z' as date-time
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    dateTimeValid(options?: { customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    dateTimeValid(callback: ServiceCallback<void>): void;
    dateTimeValid(options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get null as date-time, should result in no query parameters in uri
     * @param {object} [options] Optional Parameters.
     * @param {date} [options.dateTimeQuery] null as date-time (no query parameters)
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    dateTimeNullWithHttpOperationResponse(options?: { dateTimeQuery? : Date, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get null as date-time, should result in no query parameters in uri
     * @param {object} [options] Optional Parameters.
     * @param {date} [options.dateTimeQuery] null as date-time (no query parameters)
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    dateTimeNull(options?: { dateTimeQuery? : Date, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    dateTimeNull(callback: ServiceCallback<void>): void;
    dateTimeNull(options: { dateTimeQuery? : Date, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get an array of string ['ArrayQuery1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * csv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an array of string ['ArrayQuery1', 'begin!*'();:@
     * &=+$,/?#[]end' , null, ''] using the csv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    arrayStringCsvValidWithHttpOperationResponse(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get an array of string ['ArrayQuery1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * csv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an array of string ['ArrayQuery1', 'begin!*'();:@
     * &=+$,/?#[]end' , null, ''] using the csv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    arrayStringCsvValid(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    arrayStringCsvValid(callback: ServiceCallback<void>): void;
    arrayStringCsvValid(options: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get a null array of string using the csv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] a null array of string using the csv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    arrayStringCsvNullWithHttpOperationResponse(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get a null array of string using the csv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] a null array of string using the csv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    arrayStringCsvNull(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    arrayStringCsvNull(callback: ServiceCallback<void>): void;
    arrayStringCsvNull(options: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get an empty array [] of string using the csv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an empty array [] of string using the csv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    arrayStringCsvEmptyWithHttpOperationResponse(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get an empty array [] of string using the csv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an empty array [] of string using the csv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    arrayStringCsvEmpty(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    arrayStringCsvEmpty(callback: ServiceCallback<void>): void;
    arrayStringCsvEmpty(options: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get an array of string ['ArrayQuery1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * ssv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an array of string ['ArrayQuery1', 'begin!*'();:@
     * &=+$,/?#[]end' , null, ''] using the ssv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    arrayStringSsvValidWithHttpOperationResponse(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get an array of string ['ArrayQuery1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * ssv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an array of string ['ArrayQuery1', 'begin!*'();:@
     * &=+$,/?#[]end' , null, ''] using the ssv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    arrayStringSsvValid(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    arrayStringSsvValid(callback: ServiceCallback<void>): void;
    arrayStringSsvValid(options: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get an array of string ['ArrayQuery1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * tsv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an array of string ['ArrayQuery1', 'begin!*'();:@
     * &=+$,/?#[]end' , null, ''] using the tsv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    arrayStringTsvValidWithHttpOperationResponse(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get an array of string ['ArrayQuery1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * tsv-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an array of string ['ArrayQuery1', 'begin!*'();:@
     * &=+$,/?#[]end' , null, ''] using the tsv-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    arrayStringTsvValid(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    arrayStringTsvValid(callback: ServiceCallback<void>): void;
    arrayStringTsvValid(options: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * Get an array of string ['ArrayQuery1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * pipes-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an array of string ['ArrayQuery1', 'begin!*'();:@
     * &=+$,/?#[]end' , null, ''] using the pipes-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    arrayStringPipesValidWithHttpOperationResponse(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * Get an array of string ['ArrayQuery1', 'begin!*'();:@ &=+$,/?#[]end' , null, ''] using the
     * pipes-array format
     * @param {object} [options] Optional Parameters.
     * @param {array} [options.arrayQuery] an array of string ['ArrayQuery1', 'begin!*'();:@
     * &=+$,/?#[]end' , null, ''] using the pipes-array format
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    arrayStringPipesValid(options?: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    arrayStringPipesValid(callback: ServiceCallback<void>): void;
    arrayStringPipesValid(options: { arrayQuery? : string[], customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;
}

/**
 * @class
 * PathItems
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AutoRestUrlTestService.
 */
export interface PathItems {


    /**
     * send globalStringPath='globalStringPath', pathItemStringPath='pathItemStringPath',
     * localStringPath='localStringPath', globalStringQuery='globalStringQuery',
     * pathItemStringQuery='pathItemStringQuery', localStringQuery='localStringQuery'
     * @param {string} localStringPath should contain value 'localStringPath'
     * @param {string} pathItemStringPath A string value 'pathItemStringPath' that appears in the path
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.localStringQuery] should contain value 'localStringQuery'
     * @param {string} [options.pathItemStringQuery] A string value 'pathItemStringQuery' that appears
     * as a query parameter
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getAllWithValuesWithHttpOperationResponse(localStringPath: string, pathItemStringPath: string, options?: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * send globalStringPath='globalStringPath', pathItemStringPath='pathItemStringPath',
     * localStringPath='localStringPath', globalStringQuery='globalStringQuery',
     * pathItemStringQuery='pathItemStringQuery', localStringQuery='localStringQuery'
     * @param {string} localStringPath should contain value 'localStringPath'
     * @param {string} pathItemStringPath A string value 'pathItemStringPath' that appears in the path
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.localStringQuery] should contain value 'localStringQuery'
     * @param {string} [options.pathItemStringQuery] A string value 'pathItemStringQuery' that appears
     * as a query parameter
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getAllWithValues(localStringPath: string, pathItemStringPath: string, options?: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getAllWithValues(localStringPath: string, pathItemStringPath: string, callback: ServiceCallback<void>): void;
    getAllWithValues(localStringPath: string, pathItemStringPath: string, options: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * send globalStringPath='globalStringPath', pathItemStringPath='pathItemStringPath',
     * localStringPath='localStringPath', globalStringQuery=null,
     * pathItemStringQuery='pathItemStringQuery', localStringQuery='localStringQuery'
     * @param {string} localStringPath should contain value 'localStringPath'
     * @param {string} pathItemStringPath A string value 'pathItemStringPath' that appears in the path
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.localStringQuery] should contain value 'localStringQuery'
     * @param {string} [options.pathItemStringQuery] A string value 'pathItemStringQuery' that appears
     * as a query parameter
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getGlobalQueryNullWithHttpOperationResponse(localStringPath: string, pathItemStringPath: string, options?: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * send globalStringPath='globalStringPath', pathItemStringPath='pathItemStringPath',
     * localStringPath='localStringPath', globalStringQuery=null,
     * pathItemStringQuery='pathItemStringQuery', localStringQuery='localStringQuery'
     * @param {string} localStringPath should contain value 'localStringPath'
     * @param {string} pathItemStringPath A string value 'pathItemStringPath' that appears in the path
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.localStringQuery] should contain value 'localStringQuery'
     * @param {string} [options.pathItemStringQuery] A string value 'pathItemStringQuery' that appears
     * as a query parameter
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getGlobalQueryNull(localStringPath: string, pathItemStringPath: string, options?: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getGlobalQueryNull(localStringPath: string, pathItemStringPath: string, callback: ServiceCallback<void>): void;
    getGlobalQueryNull(localStringPath: string, pathItemStringPath: string, options: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * send globalStringPath=globalStringPath, pathItemStringPath='pathItemStringPath',
     * localStringPath='localStringPath', globalStringQuery=null,
     * pathItemStringQuery='pathItemStringQuery', localStringQuery=null
     * @param {string} localStringPath should contain value 'localStringPath'
     * @param {string} pathItemStringPath A string value 'pathItemStringPath' that appears in the path
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.localStringQuery] should contain null value
     * @param {string} [options.pathItemStringQuery] A string value 'pathItemStringQuery' that appears
     * as a query parameter
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getGlobalAndLocalQueryNullWithHttpOperationResponse(localStringPath: string, pathItemStringPath: string, options?: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * send globalStringPath=globalStringPath, pathItemStringPath='pathItemStringPath',
     * localStringPath='localStringPath', globalStringQuery=null,
     * pathItemStringQuery='pathItemStringQuery', localStringQuery=null
     * @param {string} localStringPath should contain value 'localStringPath'
     * @param {string} pathItemStringPath A string value 'pathItemStringPath' that appears in the path
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.localStringQuery] should contain null value
     * @param {string} [options.pathItemStringQuery] A string value 'pathItemStringQuery' that appears
     * as a query parameter
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getGlobalAndLocalQueryNull(localStringPath: string, pathItemStringPath: string, options?: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getGlobalAndLocalQueryNull(localStringPath: string, pathItemStringPath: string, callback: ServiceCallback<void>): void;
    getGlobalAndLocalQueryNull(localStringPath: string, pathItemStringPath: string, options: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;


    /**
     * send globalStringPath='globalStringPath', pathItemStringPath='pathItemStringPath',
     * localStringPath='localStringPath', globalStringQuery='globalStringQuery',
     * pathItemStringQuery=null, localStringQuery=null
     * @param {string} localStringPath should contain value 'localStringPath'
     * @param {string} pathItemStringPath A string value 'pathItemStringPath' that appears in the path
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.localStringQuery] should contain value null
     * @param {string} [options.pathItemStringQuery] should contain value null
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getLocalPathItemQueryNullWithHttpOperationResponse(localStringPath: string, pathItemStringPath: string, options?: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<void>>;

    /**
     * send globalStringPath='globalStringPath', pathItemStringPath='pathItemStringPath',
     * localStringPath='localStringPath', globalStringQuery='globalStringQuery',
     * pathItemStringQuery=null, localStringQuery=null
     * @param {string} localStringPath should contain value 'localStringPath'
     * @param {string} pathItemStringPath A string value 'pathItemStringPath' that appears in the path
     * @param {object} [options] Optional Parameters.
     * @param {string} [options.localStringQuery] should contain value null
     * @param {string} [options.pathItemStringQuery] should contain value null
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getLocalPathItemQueryNull(localStringPath: string, pathItemStringPath: string, options?: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }): Promise<void>;
    getLocalPathItemQueryNull(localStringPath: string, pathItemStringPath: string, callback: ServiceCallback<void>): void;
    getLocalPathItemQueryNull(localStringPath: string, pathItemStringPath: string, options: { localStringQuery? : string, pathItemStringQuery? : string, customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<void>): void;
}
