/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Class representing a MyBaseType.
 */
class MyBaseType {
  /**
   * Create a MyBaseType.
   * @property {string} [propB1]
   * @property {string} kind Polymorphic Discriminator
   * @property {string} [propBH1]
   * @property {string} kind Polymorphic Discriminator
   */
  constructor() {
  }

  /**
   * Defines the metadata of MyBaseType
   *
   * @returns {object} metadata of MyBaseType
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'MyBaseType',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'MyBaseType',
        className: 'MyBaseType',
        modelProperties: {
          propB1: {
            required: false,
            serializedName: 'propB1',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          propBH1: {
            required: false,
            serializedName: 'helper.propBH1',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MyBaseType;
