/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Pets
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AdditionalPropertiesClient.
 */
export interface Pets {


    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    createAPTrueWithHttpOperationResponse(createParameters: models.PetAPTrue, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPTrue>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    createAPTrue(createParameters: models.PetAPTrue, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPTrue>;
    createAPTrue(createParameters: models.PetAPTrue, callback: ServiceCallback<models.PetAPTrue>): void;
    createAPTrue(createParameters: models.PetAPTrue, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPTrue>): void;


    /**
     * Create a CatAPTrue which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {boolean} [createParameters.friendly]
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    createCatAPTrueWithHttpOperationResponse(createParameters: models.CatAPTrue, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.CatAPTrue>>;

    /**
     * Create a CatAPTrue which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {boolean} [createParameters.friendly]
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    createCatAPTrue(createParameters: models.CatAPTrue, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.CatAPTrue>;
    createCatAPTrue(createParameters: models.CatAPTrue, callback: ServiceCallback<models.CatAPTrue>): void;
    createCatAPTrue(createParameters: models.CatAPTrue, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.CatAPTrue>): void;


    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    createAPObjectWithHttpOperationResponse(createParameters: models.PetAPObject, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPObject>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    createAPObject(createParameters: models.PetAPObject, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPObject>;
    createAPObject(createParameters: models.PetAPObject, callback: ServiceCallback<models.PetAPObject>): void;
    createAPObject(createParameters: models.PetAPObject, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPObject>): void;


    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    createAPStringWithHttpOperationResponse(createParameters: models.PetAPString, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPString>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    createAPString(createParameters: models.PetAPString, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPString>;
    createAPString(createParameters: models.PetAPString, callback: ServiceCallback<models.PetAPString>): void;
    createAPString(createParameters: models.PetAPString, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPString>): void;


    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [createParameters.additionalProperties]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    createAPInPropertiesWithHttpOperationResponse(createParameters: models.PetAPInProperties, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPInProperties>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {object} [createParameters.additionalProperties]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    createAPInProperties(createParameters: models.PetAPInProperties, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPInProperties>;
    createAPInProperties(createParameters: models.PetAPInProperties, callback: ServiceCallback<models.PetAPInProperties>): void;
    createAPInProperties(createParameters: models.PetAPInProperties, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPInProperties>): void;


    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {string} createParameters.odatalocation
     * @param {object} [createParameters.additionalProperties1]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    createAPInPropertiesWithAPStringWithHttpOperationResponse(createParameters: models.PetAPInPropertiesWithAPString, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPInPropertiesWithAPString>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     * @param {object} createParameters
     * @param {number} createParameters.id
     * @param {string} [createParameters.name]
     * @param {string} createParameters.odatalocation
     * @param {object} [createParameters.additionalProperties1]
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    createAPInPropertiesWithAPString(createParameters: models.PetAPInPropertiesWithAPString, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPInPropertiesWithAPString>;
    createAPInPropertiesWithAPString(createParameters: models.PetAPInPropertiesWithAPString, callback: ServiceCallback<models.PetAPInPropertiesWithAPString>): void;
    createAPInPropertiesWithAPString(createParameters: models.PetAPInPropertiesWithAPString, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPInPropertiesWithAPString>): void;
}
