/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Pets
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the AdditionalPropertiesClient.
 */
export interface Pets {


    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<PetAPTrue>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    createAPTrueWithHttpOperationResponse(createParameters: models.PetAPTrue, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPTrue>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {PetAPTrue} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {PetAPTrue} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link PetAPTrue} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    createAPTrue(createParameters: models.PetAPTrue, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPTrue>;
    createAPTrue(createParameters: models.PetAPTrue, callback: ServiceCallback<models.PetAPTrue>): void;
    createAPTrue(createParameters: models.PetAPTrue, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPTrue>): void;


    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<PetAPObject>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    createAPObjectWithHttpOperationResponse(createParameters: models.PetAPObject, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPObject>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {PetAPObject} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {PetAPObject} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link PetAPObject} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    createAPObject(createParameters: models.PetAPObject, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPObject>;
    createAPObject(createParameters: models.PetAPObject, callback: ServiceCallback<models.PetAPObject>): void;
    createAPObject(createParameters: models.PetAPObject, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPObject>): void;


    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<PetAPString>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    createAPStringWithHttpOperationResponse(createParameters: models.PetAPString, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPString>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {PetAPString} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {PetAPString} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link PetAPString} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    createAPString(createParameters: models.PetAPString, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPString>;
    createAPString(createParameters: models.PetAPString, callback: ServiceCallback<models.PetAPString>): void;
    createAPString(createParameters: models.PetAPString, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPString>): void;


    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {object} [createParameters.additionalProperties]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<PetAPInProperties>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    createAPInPropertiesWithHttpOperationResponse(createParameters: models.PetAPInProperties, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPInProperties>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {object} [createParameters.additionalProperties]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {PetAPInProperties} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {PetAPInProperties} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link PetAPInProperties} for more information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    createAPInProperties(createParameters: models.PetAPInProperties, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPInProperties>;
    createAPInProperties(createParameters: models.PetAPInProperties, callback: ServiceCallback<models.PetAPInProperties>): void;
    createAPInProperties(createParameters: models.PetAPInProperties, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPInProperties>): void;


    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {string} createParameters.odatalocation
     *
     * @param {object} [createParameters.additionalProperties1]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @returns {Promise} A promise is returned
     *
     * @resolve {HttpOperationResponse<PetAPInPropertiesWithAPString>} - The deserialized result object.
     *
     * @reject {Error|ServiceError} - The error object.
     */
    createAPInPropertiesWithAPStringWithHttpOperationResponse(createParameters: models.PetAPInPropertiesWithAPString, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.PetAPInPropertiesWithAPString>>;

    /**
     * Create a Pet which contains more properties than what is defined.
     *
     * @param {object} createParameters
     *
     * @param {number} createParameters.id
     *
     * @param {string} [createParameters.name]
     *
     * @param {string} createParameters.odatalocation
     *
     * @param {object} [createParameters.additionalProperties1]
     *
     * @param {object} [options] Optional Parameters.
     *
     * @param {object} [options.customHeaders] Headers that will be added to the
     * request
     *
     * @param {ServiceCallback} [optionalCallback] - The optional callback.
     *
     * @returns {ServiceCallback|Promise} If a callback was passed as the last
     * parameter then it returns the callback else returns a Promise.
     *
     * {Promise} A promise is returned.
     *
     *                      @resolve {PetAPInPropertiesWithAPString} - The deserialized result object.
     *
     *                      @reject {Error|ServiceError} - The error object.
     *
     * {ServiceCallback} optionalCallback(err, result, request, response)
     *
     *                      {Error|ServiceError}  err        - The Error object if an error occurred, null otherwise.
     *
     *                      {PetAPInPropertiesWithAPString} [result]   - The deserialized result object if an error did not occur.
     *                      See {@link PetAPInPropertiesWithAPString} for more
     *                      information.
     *
     *                      {WebResource} [request]  - The HTTP Request object if an error did not occur.
     *
     *                      {http.IncomingMessage} [response] - The HTTP Response stream if an error did not occur.
     */
    createAPInPropertiesWithAPString(createParameters: models.PetAPInPropertiesWithAPString, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.PetAPInPropertiesWithAPString>;
    createAPInPropertiesWithAPString(createParameters: models.PetAPInPropertiesWithAPString, callback: ServiceCallback<models.PetAPInPropertiesWithAPString>): void;
    createAPInPropertiesWithAPString(createParameters: models.PetAPInPropertiesWithAPString, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.PetAPInPropertiesWithAPString>): void;
}
