/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { BaseResource, CloudError } from "ms-rest-azure";
import * as moment from "moment";

export {

  BaseResource,
  CloudError
};

export interface ErrorModel {
  status?: number;
  message?: string;
}

/**
 * Additional parameters for postRequired operation.
*/
export interface ParameterGroupingPostRequiredParameters {
  body: number;
  customHeader?: string;
  /**
   * Query parameter with default
  */
  query?: number;
  /**
   * Path parameter
  */
  path: string;
}

/**
 * Additional parameters for postOptional operation.
*/
export interface ParameterGroupingPostOptionalParameters {
  customHeader?: string;
  /**
   * Query parameter with default
  */
  query?: number;
}

/**
 * Additional parameters for a set of operations, such as: ParameterGrouping_postMultiParamGroups,
 * ParameterGrouping_postSharedParameterGroupObject.
*/
export interface FirstParameterGroup {
  headerOne?: string;
  /**
   * Query parameter with default
  */
  queryOne?: number;
}

/**
 * Additional parameters for postMultiParamGroups operation.
*/
export interface ParameterGroupingPostMultiParamGroupsSecondParamGroup {
  headerTwo?: string;
  /**
   * Query parameter with default
  */
  queryTwo?: number;
}
