/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { BaseResource, CloudError } from "ms-rest-azure";
import * as moment from "moment";

export {

  BaseResource,
  CloudError
};

export interface ErrorModel {
  status?: number;
  message?: string;
}

export interface OdataFilter {
  id?: number;
  name?: string;
}

/**
 * Additional parameters for customNamedRequestIdParamGrouping operation.
*/
export interface HeaderCustomNamedRequestIdParamGroupingParameters {
  /**
   * The fooRequestId
  */
  fooClientRequestId: string;
}
