/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

import { ServiceClientOptions, RequestOptions, ServiceCallback, HttpOperationResponse } from 'ms-rest';
import * as models from '../models';


/**
 * @class
 * Group
 * __NOTE__: An instance of this class is automatically created for an
 * instance of the MicrosoftAzureTestUrl.
 */
export interface Group {


    /**
     * Provides a resouce group with name 'testgroup101' and location 'West US'.
     * @param {string} resourceGroupName Resource Group name 'testgroup101'.
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @returns {Promise} A promise is returned.
     */
    getSampleResourceGroupWithHttpOperationResponse(resourceGroupName: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<HttpOperationResponse<models.SampleResourceGroup>>;

    /**
     * Provides a resouce group with name 'testgroup101' and location 'West US'.
     * @param {string} resourceGroupName Resource Group name 'testgroup101'.
     * @param {object} [options] Optional Parameters.
     * @param {object} [options.customHeaders] Headers that will be added to the request
     * @param {function} [optionalCallback] The optional callback.
     * @returns {function|Promise} If a callback was passed as the last parameter, then it returns the
     * callback. Otherwise it returns a Promise.
     */
    getSampleResourceGroup(resourceGroupName: string, options?: { customHeaders? : { [headerName: string]: string; } }): Promise<models.SampleResourceGroup>;
    getSampleResourceGroup(resourceGroupName: string, callback: ServiceCallback<models.SampleResourceGroup>): void;
    getSampleResourceGroup(resourceGroupName: string, options: { customHeaders? : { [headerName: string]: string; } }, callback: ServiceCallback<models.SampleResourceGroup>): void;
}
