/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as moment from "moment";

export interface ErrorModel {
  status?: number;
  message?: string;
}

export interface A {
  statusCode?: string;
}

export interface B extends A {
  textStatusCode?: string;
}

export interface C {
  httpCode?: string;
}

export interface D {
  httpStatusCode?: string;
}
