/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as moment from "moment";

/**
 * The product documentation.
 */
export interface ChildProduct {
  /**
   * Count
   */
  count?: number;
}

/**
 * The product documentation.
 */
export interface ConstantProduct {
}

/**
 * The product documentation.
 */
export interface Product {
  /**
   * Non required array of unique items from 0 to 6 elements.
   */
  displayNames?: string[];
  /**
   * Non required int betwen 0 and 100 exclusive.
   */
  capacity?: number;
  /**
   * Image URL representing the product.
   */
  image?: string;
  child: ChildProduct;
  /**
   * Constant string as Enum. Possible values include: 'constant_string_as_enum'
  */
  constStringAsEnum?: string;
}

export interface ErrorModel {
  code?: number;
  message?: string;
  fields?: string;
}
