/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as moment from "moment";


/**
 * @class
 * Initializes a new instance of the ChildProduct class.
 * @constructor
 * The product documentation.
 *
 * @property {number} [count] Count
 */
export interface ChildProduct {
  count?: number;
}

/**
 * @class
 * Initializes a new instance of the ConstantProduct class.
 * @constructor
 * The product documentation.
 *
 */
export interface ConstantProduct {
}

/**
 * @class
 * Initializes a new instance of the Product class.
 * @constructor
 * The product documentation.
 *
 * @property {array} [displayNames] Non required array of unique items from 0
 * to 6 elements.
 * @property {number} [capacity] Non required int betwen 0 and 100 exclusive.
 * @property {string} [image] Image URL representing the product.
 * @property {object} child
 * @property {number} [child.count] Count
 * @property {string} [constStringAsEnum] Constant string as Enum. Possible
 * values include: 'constant_string_as_enum'
 */
export interface Product {
  displayNames?: string[];
  capacity?: number;
  image?: string;
  child: ChildProduct;
  constStringAsEnum?: string;
}

/**
 * @class
 * Initializes a new instance of the ErrorModel class.
 * @constructor
 * @property {number} [code]
 * @property {string} [message]
 * @property {string} [fields]
 */
export interface ErrorModel {
  code?: number;
  message?: string;
  fields?: string;
}
