/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as moment from "moment";

export interface AvailabilitySetUpdateParameters {
  /**
   * @summary A set of tags.
   * @description A description about the set of tags.
  */
  tags: { [propertyName: string]: string };
}
