/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as moment from "moment";


/**
 * @class
 * Initializes a new instance of the Widget class.
 * @constructor
 * @property {number} [integer]
 * @property {string} [string]
 */
export interface Widget {
  integer?: number;
  string?: string;
}

/**
 * @class
 * Initializes a new instance of the ErrorModel class.
 * @constructor
 * @property {number} [status]
 * @property {string} [message]
 */
export interface ErrorModel {
  status?: number;
  message?: string;
}
