/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Class representing a MyDerivedType.
 * @extends models['MyBaseType']
 */
class MyDerivedType extends models['MyBaseType'] {
  /**
   * Create a MyDerivedType.
   * @member {string} [propD1]
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of MyDerivedType
   *
   * @returns {object} metadata of MyDerivedType
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Kind1',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'kind',
          clientName: 'kind'
        },
        uberParent: 'MyBaseType',
        className: 'MyDerivedType',
        modelProperties: {
          propB1: {
            required: false,
            serializedName: 'propB1',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          propBH1: {
            required: false,
            serializedName: 'helper.propBH1',
            type: {
              name: 'String'
            }
          },
          kind: {
            required: true,
            serializedName: 'kind',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          propD1: {
            required: false,
            serializedName: 'propD1',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = MyDerivedType;
