/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as moment from "moment";

export interface ErrorModel {
  status?: number;
  message?: string;
}

export interface IntWrapper {
  value: number;
}

export interface IntOptionalWrapper {
  value?: number;
}

export interface StringWrapper {
  value: string;
}

export interface StringOptionalWrapper {
  value?: string;
}

export interface ArrayWrapper {
  value: string[];
}

export interface ArrayOptionalWrapper {
  value?: string[];
}

export interface Product {
  id: number;
  name?: string;
}

export interface ClassWrapper {
  value: Product;
}

export interface ClassOptionalWrapper {
  value?: Product;
}
